# Find all the information you need at http://dev.thomasvdbulk.nl/KoTH/

# To grab your own timezone go to: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

global:
  use-cache: true
  debug: true
  multiplekothsatonce: true
  schedule-show-current-day-only: false
  schedule-timezone: "Europe/London"
  date-format: "dd/MM/yyyy HH:mm:ss"
  minuteoffset: 0
  startweekminuteoffset: 0
  scheduleminuteoffset: 0
  pre-broadcast: 0
  nocap-broadcast-interval: 30
  helpcommand:
    - "&8========> &2Koth &8<========"
    - "&a/koth list &7Shows all available koths"
    - "&a/koth loot &7Shows the loot for the upcoming koth"
    - "&a/koth schedule &7Shows the schedule for koths"
    - "&a/koth ignore &7Toggles the KoTH messages"

loot:
  default: ""
  randomize: true
  default-amount: 5
  randomize-stacksize: false
  can-use-same-items: true
  remove-after: 0
  drop-on-removal: false
  give-instantly: false
  commands:
    enabled: false
    changeingame: false
    needop: true

hooks:
  vanishnopacket: true
  factions: true
  kingdoms: true
  gangs: true
  pvpmanager: true
  featherboard:
    enabled: true
    board: "KOTH"
    range: 100 # -1 to disable it
    rangemargin: 5

koth:
  remove-chest-at-start: true
  ffa-on-time-limit: false # This will on time limit create a FreeForAll chest
  default-capturetype: "" # set this to your desired capture type
  contest-freeze: false
  capture-cooldown: 0
  channel-time: 0
  knock-time: 0
  minimum-players: 0
  map-rotation:
    - "map1"
    - "map2"
    - "map3"
    - "map2"
    - "etc"

# If you use SQLite only database will be used, as name for the file to create
# change storagetype to mysql if you want to use MySQL instead.
database:
  enabled: false
  storagetype: "sqlite"
  database: "KoTH"
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
